# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('errorCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_lat', models.FloatField()),
                ('gps_lon', models.FloatField()),
                ('last_seen', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationName', models.CharField(max_length=100)),
                ('applicationID', models.UUIDField()),
                ('devEUI', models.UUIDField()),
                ('nodeName', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('fCnt', models.IntegerField()),
                ('fPort', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_eui', models.CharField(max_length=100)),
                ('app_key', models.CharField(max_length=100)),
                ('dev_addr', models.CharField(max_length=100)),
                ('dev_eui', models.CharField(max_length=100)),
                ('last_seen', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('last_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('gateways', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gateway')),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Node')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('loRaSNR', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('gatwayMac', models.UUIDField()),
                ('gatwayName', models.CharField(max_length=100)),
                ('rssi', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='Swarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Node')),
            ],
        ),
        migrations.CreateModel(
            name='TxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr', models.BooleanField(default=False)),
                ('codeRate', models.CharField(max_length=10)),
                ('bandwidth', models.IntegerField(default=0)),
                ('modulation', models.CharField(max_length=10)),
                ('spreadFactor', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Node'),
        ),
        migrations.AddField(
            model_name='message',
            name='rxInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RxInfo'),
        ),
        migrations.AddField(
            model_name='message',
            name='txInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TxInfo'),
        ),
    ]
