# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationName', models.CharField(max_length=100)),
                ('applicationID', models.UUIDField()),
                ('devEUI', models.UUIDField()),
                ('data', models.TextField()),
                ('fCnt', models.IntegerField()),
                ('fPort', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('errorCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_lat', models.FloatField()),
                ('gps_lon', models.FloatField()),
                ('last_seen', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_eui', models.CharField(max_length=100)),
                ('app_key', models.CharField(max_length=100)),
                ('dev_addr', models.CharField(max_length=100)),
                ('dev_eui', models.CharField(max_length=100)),
                ('last_seen', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('last_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='RxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('loRaSNR', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('mac', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('rssi', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Swarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Node')),
            ],
        ),
        migrations.CreateModel(
            name='TxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr', models.BooleanField()),
                ('codeRate', models.CharField(max_length=10)),
                ('bandwidth', models.IntegerField()),
                ('modulation', models.CharField(max_length=10)),
                ('spreadFactor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('registered', models.CharField(max_length=100)),
                ('gateways', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gateway')),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Node')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gateway'),
        ),
        migrations.AddField(
            model_name='data',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Node'),
        ),
        migrations.AddField(
            model_name='data',
            name='rxInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RxInfo'),
        ),
        migrations.AddField(
            model_name='data',
            name='txInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TxInfo'),
        ),
    ]
