# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationName', models.CharField(max_length=100)),
                ('applicationID', models.UUIDField()),
                ('devEUI', models.UUIDField()),
                ('data', models.TextField()),
                ('fCnt', models.IntegerField()),
                ('fPort', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gateway')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Node')),
                ('rxInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RxInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('gateways', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gateway')),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Node')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='gateways',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nodes',
        ),
        migrations.AddField(
            model_name='txinfo',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='txinfo',
            name='adr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='txinfo',
            name='bandwidth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='txinfo',
            name='spreadFactor',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='txInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TxInfo'),
        ),
    ]
