# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170427_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='gps_lat',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gps_lon',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='last_seen',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='mac',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='app_eui',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='dev_eui',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='rxinfo',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='rxinfo',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
