# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170607_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 19, 14, 40, 336216)),
        ),
        migrations.AlterField(
            model_name='node',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 19, 14, 40, 337031)),
        ),
    ]
