# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170607_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rxinfo',
            old_name='gatwayMac',
            new_name='gatewayMac',
        ),
        migrations.RenameField(
            model_name='rxinfo',
            old_name='gatwayName',
            new_name='gatewayName',
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gps_lat',
            field=models.DecimalField(decimal_places=8, help_text='Latitudinal coordinate of the gateway.', max_digits=11),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gps_lon',
            field=models.DecimalField(decimal_places=8, help_text='Longitudinal coordinate of the gateway.', max_digits=11),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 20, 20, 31, 833713)),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='mac',
            field=models.UUIDField(help_text="The device's MAC address."),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='serial',
            field=models.CharField(help_text="The device's serial number", max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 20, 20, 31, 834212)),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(help_text='Company Name', max_length=100),
        ),
    ]
