# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170607_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 20, 6, 50, 101315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='node',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 20, 6, 50, 102015, tzinfo=utc)),
        ),
    ]
